### PR TITLE
Fix for issue to handle + in the job name

### PR DESCRIPTION
**Pull request by mohdnisart**
Fixed issue #2, with job name having + sign

**Affects:** \<jenkins-collector-version-number>.

* [Individual Agreement](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform)
* [Corporate Agreement](https://docs.google.com/forms/d/e/1FAIpQLSeAbobIPLCVZD_ccgtMWBDAcN68oqbAJBQyDTSAQ1AkYuCp_g/viewform?usp=send_form)

- [x] I Have signed the CLA

---

### CODE REVIEW

**Comment by mohdnisart** [comment]
#2

**Comment by mohdnisart** [comment]
@rvema/Team: Kindly help to merge the code

**Comment by rvema** [comment]
@mohdnisart Any specific reason behind String replace in place of URL encode?

**Comment by mohdnisart** [comment]
> @mohdnisart Any specific reason behind String replace in place of URL encode?

@rvema more explanation [here ](https://stackoverflow.com/questions/4737841/urlencoder-not-able-to-translate-space-character):

**Comment by rvema** [comment]
Thanks @mohdnisart I will get this merged today

**Pull request merged**
